Repository moderntribe/moose, pull requests merged in 2023-08, with the labels that each got.

#78 [MOOSE-38] Post Cards QA
  wp-content/plugins/core/src/Theme_Config/Theme_Config_Subscriber.php
Labels: Needs BE Review

#77 [MOOSE-36] Search Results Template QA
  wp-content/plugins/core/src/Blocks/Blocks_Definer.php
  wp-content/themes/core/blocks/core/search/Search.php
  wp-content/themes/core/blocks/core/search/index.js
  wp-content/themes/core/blocks/core/search/style.pcss
  wp-content/themes/core/blocks/tribe/query-results-count/render.php
  wp-content/themes/core/blocks/tribe/query-results-count/style.pcss
  wp-content/themes/core/parts/pagination.html
  wp-content/themes/core/templates/search.html
Labels: Needs FE Review

#75 [TRY] Column Block Stacking Order
  CHANGELOG.md
  wp-content/plugins/core/src/Blocks/Blocks_Definer.php
  wp-content/themes/core/assets/js/admin/block-animation.js
  wp-content/themes/core/assets/js/admin/ready.js
  wp-content/themes/core/assets/js/theme/ready.js
  wp-content/themes/core/assets/js/utils/animate-on-scroll.js
  wp-content/themes/core/assets/pcss/global/animation.pcss
  wp-content/themes/core/assets/pcss/global/stacking-order.pcss
  wp-content/themes/core/assets/pcss/theme.pcss
  wp-content/themes/core/blocks/core/column/Column.php
  wp-content/themes/core/blocks/core/column/admin.js
Labels: Needs FE Review

#84 [CHORE] WP Core / Composer Packages Update
  .env.sample
  .gitignore
  .lando.yml
  CHANGELOG.md
  README.md
  auth-sample.json
  composer.json
  composer.lock
Labels: Needs FE Review, Needs BE Review

#86 [FIX] WP 6.3 Block Styles Support
  wp-content/plugins/core/src/Theme_Config/Theme_Support.php
  wp-content/themes/core/blocks/core/lists/style.pcss
  wp-content/themes/core/theme.json
Labels: Needs FE Review, Needs BE Review

#88 Setup dokku for auth.json
  .github/workflows/dokku-dev.yml
  .github/workflows/dokku-review-app.yml
  .github/workflows/pipeline-dokku.yml
Labels: Launch Environment

#76 [MOOSE-32] Post Single Template
  wp-content/plugins/core/src/Blocks/Blocks_Definer.php
  wp-content/plugins/core/src/Blocks/Blocks_Subscriber.php
  wp-content/plugins/core/src/Blocks/Filters/Contracts/Block_Content_Filter.php
  wp-content/plugins/core/src/Core.php
  wp-content/plugins/core/src/Post_Types/Post/Config.php
  wp-content/plugins/core/src/Post_Types/Post/Post.php
  wp-content/plugins/core/src/Post_Types/Post/Post_Subscriber.php
  wp-content/themes/core/assets/pcss/typography/_mixins.pcss
  wp-content/themes/core/blocks/core/postauthorname/Post_Author_Name.php
  wp-content/themes/core/blocks/core/postauthorname/index.js
  wp-content/themes/core/blocks/core/postauthorname/style.pcss
  wp-content/themes/core/blocks/core/postterms/style.pcss
  wp-content/themes/core/patterns/post.php
  wp-content/themes/core/templates/page.html
  wp-content/themes/core/templates/single.html
Labels: Needs FE Review

#79 [MOOSE-34] Post Archive Templates
  wp-content/plugins/core/src/Blocks/Blocks_Definer.php
  wp-content/themes/core/assets/pcss/cards/post.pcss
  wp-content/themes/core/blocks/core/posttemplate/Post_Template.php
  wp-content/themes/core/blocks/core/posttemplate/index.js
  wp-content/themes/core/blocks/core/posttemplate/style.pcss
  wp-content/themes/core/templates/archive.html
  wp-content/themes/core/templates/index.html
Labels: Needs FE Review

#91 [MOOSE-32] Single Post Template Fixes
  wp-content/themes/core/assets/js/admin/block-animation.js
  wp-content/themes/core/assets/js/admin/ready.js
  wp-content/themes/core/blocks/core/postauthorname/style.pcss
  wp-content/themes/core/patterns/post.php
  wp-content/themes/core/templates/archive.html
  wp-content/themes/core/templates/index.html
Labels: Needs FE Review

#94 [FIX] Update Styleguide Pattern for WP 6.3
  wp-content/plugins/core/src/Blocks/Blocks_Definer.php
  wp-content/themes/core/blocks/core/pullquote/Pullquote.php
  wp-content/themes/core/blocks/core/pullquote/index.js
  wp-content/themes/core/blocks/core/pullquote/style.pcss
  wp-content/themes/core/blocks/core/quote/index.js
  wp-content/themes/core/blocks/core/quote/style.pcss
  wp-content/themes/core/patterns/styleguide.php
  wp-content/themes/core/theme.json
Labels: Needs FE Review
