Repository moderntribe/moose, pull requests merged in 2025-10, with the labels that each got.

#250 [MOOSE-258] Alternate Post Single Template
  wp-content/plugins/core/src/Core.php
  wp-content/plugins/core/src/Post_Types/Post/Config.php
  wp-content/plugins/core/src/Post_Types/Post/Post_Subscriber.php
  wp-content/themes/core/patterns/post-left-aligned.php
  wp-content/themes/core/theme.json
Labels: Launch Environment, In QA

#247 [MOOSE-270] Related Posts Block
  wp-content/plugins/core/src/Blocks/Blocks_Definer.php
  wp-content/plugins/core/src/Core.php
  wp-content/plugins/core/src/Post_Types/Post/Config.php
  wp-content/plugins/core/src/Post_Types/Post/Post_Subscriber.php
  wp-content/themes/core/blocks/tribe/related-posts/block.json
  wp-content/themes/core/blocks/tribe/related-posts/edit.js
  wp-content/themes/core/blocks/tribe/related-posts/index.js
  wp-content/themes/core/blocks/tribe/related-posts/render.php
  wp-content/themes/core/blocks/tribe/related-posts/style.pcss
  wp-content/themes/core/blocks/tribe/terms/edit.js
  wp-content/themes/core/components/cards/post.php
  wp-content/themes/core/patterns/post-left-aligned.php
  wp-content/themes/core/patterns/post.php
  wp-content/themes/core/theme.json
Labels: Launch Environment, In QA

#255 [MOOSE-259] Static Image Overlay Card Block
  wp-content/plugins/core/src/Blocks/Blocks_Definer.php
  wp-content/themes/core/blocks/tribe/image-overlay-card/_mixins.pcss
  wp-content/themes/core/blocks/tribe/image-overlay-card/block.json
  wp-content/themes/core/blocks/tribe/image-overlay-card/edit.js
  wp-content/themes/core/blocks/tribe/image-overlay-card/editor.pcss
  wp-content/themes/core/blocks/tribe/image-overlay-card/index.js
  wp-content/themes/core/blocks/tribe/image-overlay-card/render.php
  wp-content/themes/core/blocks/tribe/image-overlay-card/style.pcss
Labels: Needs FE Review, Launch Environment

#254 [MOOSE-261] Static Image Card Custom Block
  webpack.config.js
  wp-content/plugins/core/src/Blocks/Blocks_Definer.php
  wp-content/themes/core/blocks/tribe/image-card/_mixins.pcss
  wp-content/themes/core/blocks/tribe/image-card/block.json
  wp-content/themes/core/blocks/tribe/image-card/edit.js
  wp-content/themes/core/blocks/tribe/image-card/editor.pcss
  wp-content/themes/core/blocks/tribe/image-card/index.js
  wp-content/themes/core/blocks/tribe/image-card/render.php
  wp-content/themes/core/blocks/tribe/image-card/style.pcss
Labels: Needs FE Review, Launch Environment

#253 [MOOSE-156] Masthead (DQA)
  wp-content/themes/core/assets/pcss/media-queries/_variables.pcss
  wp-content/themes/core/assets/pcss/navigation/mega-menu.pcss
  wp-content/themes/core/assets/pcss/parts/header.pcss
  wp-content/themes/core/blocks/tribe/masthead-search/view.js
  wp-content/themes/core/blocks/tribe/mega-menu-item/style.pcss
  wp-content/themes/core/blocks/tribe/menu-toggle/style.pcss
  wp-content/themes/core/blocks/tribe/navigation-link/style.pcss
  wp-content/themes/core/blocks/tribe/standard-menu-item/style.pcss
  wp-content/themes/core/parts/footer.html
  wp-content/themes/core/theme.json
Labels: Launch Environment
